// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: '************************************',
      authDomain: '********************************',
      databaseURL:
          'https://smart-sprinkler-eb66c-default-rtdb.asia-southeast1.firebasedatabase.app',
      projectId: 'smart-sprinkler-eb66c',
      storageBucket: 'smart-sprinkler-eb66c.appspot.com',
      messagingSenderId: '404202523795',
      appId: '1:404202523795:web:e732ed3c0f35e66d0f9166',
      measurementId: 'G-ENVXGLBNX2');

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: '*************************************',
      authDomain: 's*******************************',
      databaseURL:
          'https://smart-sprinkler-eb66c-default-rtdb.asia-southeast1.firebasedatabase.app',
      appId: '1:404202523795:android:ce7073af0bdfafb90f9166',
      messagingSenderId: '404202523795',
      projectId: 'smart-sprinkler-eb66c',
      measurementId: 'G-ENVXGLBNX2',
      storageBucket: 'smart-sprinkler-eb66c.appspot.com');
}
